import { useEffect, useRef } from "react";
import { Route } from "wouter";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ScrollToPlugin } from "gsap/ScrollToPlugin";
import VideoBackground from "./components/VideoBackground";
import TextOverlay from "./components/TextOverlay";
import Navbar from "./components/Navbar";
import ScrollProgress from "./components/ScrollProgress";
import IDEPage from "./pages/IDEPage";
import { ScrollContext } from "./ScrollContext";

gsap.registerPlugin(ScrollTrigger, ScrollToPlugin);

const SNAP_TARGETS = [0, 30, 60, 75, 93];
const SNAP_DELAY_MS = 180;

function useScrollSnap(containerRef: React.RefObject<HTMLDivElement | null>) {
  useEffect(() => {
    let timeoutId: ReturnType<typeof setTimeout>;
    let lastScrollTop = 0;
    let scrollDir = 1;
    let gsapScrolling = false;

    // Always snaps in the direction of travel — never bounces backwards.
    const getSnapTarget = (currentPct: number, dir: number): number => {
      if (dir > 0) {
        return SNAP_TARGETS.find((t) => t > currentPct) ?? SNAP_TARGETS[SNAP_TARGETS.length - 1];
      } else {
        return [...SNAP_TARGETS].reverse().find((t) => t < currentPct) ?? SNAP_TARGETS[0];
      }
    };

    const onScroll = () => {
      const container = containerRef.current;
      if (!container) return;

      // Ignore scroll events generated by GSAP to prevent cascade
      if (gsapScrolling) return;

      scrollDir = container.scrollTop > lastScrollTop ? 1 : -1;
      lastScrollTop = container.scrollTop;

      clearTimeout(timeoutId);
      timeoutId = setTimeout(() => {
        const c = containerRef.current;
        if (!c) return;
        const scrollableH = c.scrollHeight - c.clientHeight;
        if (scrollableH <= 0) return;
        const currentPct = (c.scrollTop / scrollableH) * 100;
        const targetPct = getSnapTarget(currentPct, scrollDir);
        const targetY = (targetPct / 100) * scrollableH;

        gsapScrolling = true;
        gsap.to(c, {
          scrollTo: { y: targetY },
          duration: 0.28,
          ease: "power2.out",
          onComplete: () => { gsapScrolling = false; },
          onInterrupt: () => { gsapScrolling = false; },
        });
      }, SNAP_DELAY_MS);
    };

    const attach = (container: HTMLDivElement) => {
      container.addEventListener("scroll", onScroll, { passive: true });
    };
    const detach = (container: HTMLDivElement) => {
      container.removeEventListener("scroll", onScroll);
      clearTimeout(timeoutId);
      gsapScrolling = false;
      gsap.killTweensOf(container);
    };

    let activeContainer: HTMLDivElement | null = null;

    const sync = () => {
      const isDesktop = window.innerWidth >= 768;
      const container = containerRef.current;
      if (!container) return;
      if (isDesktop && activeContainer !== container) {
        if (activeContainer) detach(activeContainer);
        attach(container);
        activeContainer = container;
      } else if (!isDesktop && activeContainer) {
        detach(activeContainer);
        activeContainer = null;
      }
    };

    const initId = setTimeout(sync, 0);
    window.addEventListener("resize", sync);

    return () => {
      clearTimeout(initId);
      clearTimeout(timeoutId);
      window.removeEventListener("resize", sync);
      if (activeContainer) detach(activeContainer);
    };
  }, [containerRef]);
}

function HomePage() {
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const timer = setTimeout(() => {
      ScrollTrigger.refresh();
    }, 500);
    return () => clearTimeout(timer);
  }, []);

  useScrollSnap(scrollRef);

  return (
    <ScrollContext value={scrollRef}>
      <div
        ref={scrollRef}
        style={{
          position: "fixed",
          inset: 0,
          overflowY: "scroll",
          backgroundColor: "#0a0a0a",
        }}
      >
        <VideoBackground />
        <ScrollProgress />
        <Navbar />
        <TextOverlay />
      </div>
    </ScrollContext>
  );
}

export default function App() {
  return (
    <>
      <Route path="/" component={HomePage} />
      <Route path="/ide" component={IDEPage} />
    </>
  );
}
